
#the structure of RvTools heavily based on crystools: https://raw.githubusercontent.com/crystian/ComfyUI-Crystools

from .core import version, logger
logger.info(f'RvTools version: {version}')

from .nodes._names import CLASSES
from .nodes.primitive import RBoolean, RText, RTextML, RInteger, RFloat
from .nodes.switch import RSwitchAudio, RSwitchBus, RSwitchClip, RSwitchSampler, RSwitchSampler_Restart, RSwitchScheduler, \
    RSwitchScheduler_Impact, RSwitchScheduler_Efficient, RSwitchScheduler_Restart, RSwitchBasicPipe, RSwitchConditioning, RSwitchControlNet, \
    RSwitchDetailerPipe, RSwitchFloat, RSwitchGuider, RSwitchImage, RSwitchInteger, RSwitchLatent, RSwitchMask, RSwitchModel, RSwitchString, RSwitchVAE, \
    RMultiSwitch_Model, RMultiSwitch_CLIP, RMultiSwitch_VAE, RMultiSwitch_Latent

from .nodes.image import RImageBatchToList, RImageListToBatch, RImagesToRGB, RMaskBatchToList, RMaskListToBatch
from .nodes.folders import RProjectFolder, RFolderAdd, RFileNamePrefixAdd
from .nodes.selector import RSamplerSelector, RSamplerSelector_Restart, RSchedulerSelector_ComfyUI_Impact, RSchedulerSelector_ComfyUI, \
    RSchedulerSelector_Efficient, RSchedulerSelector_Efficient_Impact, RSchedulerSelector_Impact, RSchedulerSelector_Restart

from .nodes.passer import RPassAudio, RPassBasicPipe, RPassClip, RPassConditioning, RPassDetailerPipe, RPassFloat, RPassImages, RPassInteger, RPassLatent, \
    RPassMasks, RPassModel, RPassPipeLine, RPassString, RPassSampler, RPassScheduler_ComfyIU, RPassScheduler_Impact, RPassSamplerRestart, \
    RPassScheduler_Efficient, RPassScheduler_Restart

from .nodes.utils import RBusAny12CH_IN, RBusAny12CH_OUT, RBusAny8CH_IN, RBusAny8CH_OUT, RMergeStrings, RMergeStringsLarge, RReplaceString, RComboToString, \
    RFloatToInteger, RFloatToString, RIntegerToString, RSizesPlusXYOffset, RStringListToCombo, RIfExecute


NODE_CLASS_MAPPINGS = {
    #primitives
    CLASSES.RBOOLEAN_NAME.value: RBoolean,
    CLASSES.RFLOAT_NAME.value: RFloat,
    CLASSES.RINTEGER_NAME.value: RInteger,
    CLASSES.RTEXT_NAME.value: RText,
    CLASSES.RTEXTML_NAME.value: RTextML,
    #folder
    CLASSES.RPROJECTFOLDER_NAME.value: RProjectFolder,
    CLASSES.RFOLDER_ADD_NAME.value: RFolderAdd,
    CLASSES.RFILENAME_PREFIX_ADD_NAME.value: RFileNamePrefixAdd,
    #selector sampler
    CLASSES.RSAMPLER_SELECTOR_NAME.value: RSamplerSelector,
    CLASSES.RSAMPLER_SELECTOR_RESTART_NAME.value: RSamplerSelector_Restart,
    #selector scheduler
    CLASSES.RSCHEDULER_SELECTOR_COMFYUI_NAME.value: RSchedulerSelector_ComfyUI,
    CLASSES.RSCHEDULER_SELECTOR_EFFICIENT_NAME.value: RSchedulerSelector_Efficient,
    CLASSES.RSCHEDULER_SELECTOR_IMPACT_NAME.value: RSchedulerSelector_Impact,
    CLASSES.RSCHEDULER_SELECTOR_RESTART_NAME.value: RSchedulerSelector_Restart,
    CLASSES.RSCHEDULER_SELECTOR_COMFYUI_IMPACT_NAME.value: RSchedulerSelector_ComfyUI_Impact,
    CLASSES.RSCHEDULER_SELECTOR_EFFICIENT_IMPACT_NAME.value: RSchedulerSelector_Efficient_Impact,
    #sampler switch
    CLASSES.RSAMPLER_SWITCH_NAME.value: RSwitchSampler,
    CLASSES.RSAMPLER_SWITCH_RESTART_NAME.value: RSwitchSampler_Restart,
    #scheduler switch
    CLASSES.RSCHEDULER_SWITCH_NAME.value: RSwitchScheduler,
    CLASSES.RSCHEDULER_SWITCH_IMPACT_NAME.value: RSwitchScheduler_Impact,
    CLASSES.RSCHEDULER_SWITCH_EFFICIENT_NAME.value: RSwitchScheduler_Efficient,
    CLASSES.RSCHEDULER_SWITCH_RESTART_NAME.value: RSwitchScheduler_Restart,
    #operation/conversion
    CLASSES.RIMAGES_TO_RGB_NAME.value: RImagesToRGB,
    CLASSES.RIMAGELIST_TO_BATCH_NAME.value: RImageListToBatch,
    CLASSES.RIMAGEBATCH_TO_LIST_NAME.value: RImageBatchToList,
    CLASSES.RMASKLIST_TO_BATCH_NAME.value: RMaskListToBatch,
    CLASSES.RMASKBATCH_TO_LIST_NAME.value: RMaskBatchToList,
    #switches
    CLASSES.RSWITCH_AUDIO_NAME.value: RSwitchAudio,
    CLASSES.RSWITCH_BUS_NAME.value: RSwitchBus,
    CLASSES.RSWITCH_CLIP_NAME.value: RSwitchClip,
    CLASSES.RSWITCH_CONDITIONING_NAME.value: RSwitchConditioning,
    CLASSES.RSWITCH_CONTROLNET_NAME.value: RSwitchControlNet,
    CLASSES.RSWITCH_FLOAT_NAME.value: RSwitchFloat,
    CLASSES.RSWITCH_GUIDER_NAME.value: RSwitchGuider,
    CLASSES.RSWITCH_IMAGE_NAME.value: RSwitchImage,
    CLASSES.RSWITCH_INTEGER_NAME.value: RSwitchInteger,
    CLASSES.RSWITCH_LATENT_NAME.value: RSwitchLatent,
    CLASSES.RSWITCH_MASK_NAME.value: RSwitchMask,
    CLASSES.RSWITCH_MODEL_NAME.value: RSwitchModel,
    CLASSES.RSWITCH_BASIC_PIPE_NAME.value: RSwitchBasicPipe,
    CLASSES.RSWITCH_DETAILER_PIPE_NAME.value: RSwitchDetailerPipe,
    CLASSES.RSWITCH_STRING_NAME.value: RSwitchString,
    CLASSES.RSWITCH_VAE_NAME.value: RSwitchVAE,
    CLASSES.RMULTISWITCH_MODEL_NAME.value: RMultiSwitch_Model,
    CLASSES.RMULTISWITCH_CLIP_NAME.value: RMultiSwitch_CLIP,
    CLASSES.RMULTISWITCH_VAE_NAME.value: RMultiSwitch_VAE,
    CLASSES.RMULTISWITCH_LATENT_NAME.value: RMultiSwitch_Latent,

    #passer
    CLASSES.RPASS_AUDIO_NAME.value: RPassAudio,
    CLASSES.RPASS_CLIP_NAME.value: RPassClip,
    CLASSES.RPASS_CONDITIONING_NAME.value: RPassConditioning,
    CLASSES.RPASS_FLOAT_NAME.value: RPassFloat,
    CLASSES.RPASS_IMAGE_NAME.value: RPassImages,
    CLASSES.RPASS_INTEGER_NAME.value: RPassInteger,
    CLASSES.RPASS_LATENT_NAME.value: RPassLatent,
    CLASSES.RPASS_MASK_NAME.value: RPassMasks,
    CLASSES.RPASS_MODEL_NAME.value: RPassModel,
    CLASSES.RPASS_PIPE_BASIC_NAME.value: RPassBasicPipe,
    CLASSES.RPASS_PIPE_DETAILER_NAME.value: RPassDetailerPipe,
    CLASSES.RPASS_PIPE_LINE_NAME.value: RPassPipeLine,
    CLASSES.RPASS_STRING_NAME.value: RPassString,
    CLASSES.RPASS_SAMPLER_NAME.value: RPassSampler,
    CLASSES.RPASS_SCHEDULER_COMFYUI_NAME.value: RPassScheduler_ComfyIU,
    CLASSES.RPASS_SCHEDULER_IMPACT_NAME.value: RPassScheduler_Impact,
    CLASSES.RPASS_SCHEDULER_EFFICIENT_NAME.value: RPassScheduler_Efficient,
    CLASSES.RPASS_SCHEDULER_RESTART_NAME.value: RPassScheduler_Restart,
    #utils
    CLASSES.RBUS_ANY_8CH_IN_NAME.value: RBusAny8CH_IN,
    CLASSES.RBUS_ANY_8CH_OUT_NAME.value: RBusAny8CH_OUT,
    CLASSES.RBUS_ANY_12CH_IN_NAME.value: RBusAny12CH_IN,
    CLASSES.RBUS_ANY_12CH_OUT_NAME.value: RBusAny12CH_OUT,
    CLASSES.RREPLACE_STRING_NAME.value: RReplaceString,
    CLASSES.RMERGE_STRING_NAME.value: RMergeStrings,
    CLASSES.RMERGE_STRING_LARGE_NAME.value: RMergeStringsLarge,
    CLASSES.RINTEGER_TO_STRING_NAME.value: RIntegerToString,
    CLASSES.RFLOAT_TO_STRING_NAME.value: RFloatToString,
    CLASSES.RFLOAT_TO_INTEGER_NAME.value: RFloatToInteger,
    CLASSES.RSIZES_PLUS_XY_NAME.value: RSizesPlusXYOffset,
    CLASSES.RSTRINGLIST_TO_COMBO_NAME.value: RStringListToCombo,
    CLASSES.RCOMBO_TO_STRING_NAME.value: RComboToString,
    CLASSES.RIFEXECUTE_NAME.value: RIfExecute,
    
}

NODE_DISPLAY_NAME_MAPPINGS = {
    #primitives
    CLASSES.RFLOAT_NAME.value: CLASSES.RFLOAT_DESC.value,
    CLASSES.RINTEGER_NAME.value: CLASSES.RINTEGER_DESC.value,
    CLASSES.RTEXT_NAME.value: CLASSES.RTEXT_DESC.value,
    CLASSES.RTEXTML_NAME.value: CLASSES.RTEXTML_DESC.value,
    #folder
    CLASSES.RPROJECTFOLDER_NAME.value: CLASSES.RPROJECTFOLDER_DESC.value,
    CLASSES.RFOLDER_ADD_NAME.value: CLASSES.RFOLDER_ADD_DESC.value,
    CLASSES.RFILENAME_PREFIX_ADD_NAME.value: CLASSES.RFILENAME_PREFIX_ADD_DESC.value,
    #selector
    CLASSES.RSAMPLER_SELECTOR_NAME.value: CLASSES.RSAMPLER_SELECTOR_DESC.value,
    CLASSES.RSAMPLER_SELECTOR_RESTART_NAME.value: CLASSES.RSAMPLER_SELECTOR_RESTART_DESC.value,
    #selector scheduler
    CLASSES.RSCHEDULER_SELECTOR_COMFYUI_NAME.value: CLASSES.RSCHEDULER_SELECTOR_COMFYUI_DESC.value,
    CLASSES.RSCHEDULER_SELECTOR_EFFICIENT_NAME.value: CLASSES.RSCHEDULER_SELECTOR_EFFICIENT_DESC.value,
    CLASSES.RSCHEDULER_SELECTOR_IMPACT_NAME.value: CLASSES.RSCHEDULER_SELECTOR_IMPACT_DESC.value,
    CLASSES.RSCHEDULER_SELECTOR_RESTART_NAME.value: CLASSES.RSCHEDULER_SELECTOR_RESTART_DESC.value,
    CLASSES.RSCHEDULER_SELECTOR_COMFYUI_IMPACT_NAME.value: CLASSES.RSCHEDULER_SELECTOR_COMFYUI_IMPACT_DESC.value,
    CLASSES.RSCHEDULER_SELECTOR_EFFICIENT_IMPACT_NAME.value: CLASSES.RSCHEDULER_SELECTOR_EFFICIENT_IMPACT_DESC.value,
    #sampler switch
    CLASSES.RSAMPLER_SWITCH_NAME.value:CLASSES.RSAMPLER_SWITCH_DESC.value,
    CLASSES.RSAMPLER_SWITCH_RESTART_NAME.value:CLASSES.RSAMPLER_SWITCH_RESTART_DESC.value,
    #scheduler switch
    CLASSES.RSCHEDULER_SWITCH_NAME.value:CLASSES.RSCHEDULER_SWITCH_DESC.value,
    CLASSES.RSCHEDULER_SWITCH_IMPACT_NAME.value:CLASSES.RSCHEDULER_SWITCH_IMPACT_DESC.value,
    CLASSES.RSCHEDULER_SWITCH_EFFICIENT_NAME.value:CLASSES.RSCHEDULER_SWITCH_EFFICIENT_DESC.value,
    CLASSES.RSCHEDULER_SWITCH_RESTART_NAME.value:CLASSES.RSCHEDULER_SWITCH_RESTART_DESC.value,
    #operation/conversion
    CLASSES.RIMAGES_TO_RGB_NAME.value: CLASSES.RIMAGES_TO_RGB_DESC.value,
    CLASSES.RIMAGELIST_TO_BATCH_NAME.value: CLASSES.RIMAGELIST_TO_BATCH_DESC.value,
    CLASSES.RIMAGEBATCH_TO_LIST_NAME.value: CLASSES.RIMAGEBATCH_TO_LIST_DESC.value,
    CLASSES.RMASKLIST_TO_BATCH_NAME.value: CLASSES.RMASKLIST_TO_BATCH_DESC.value,
    CLASSES.RMASKBATCH_TO_LIST_NAME.value: CLASSES.RMASKBATCH_TO_LIST_DESC.value,
    #switches
    CLASSES.RSWITCH_AUDIO_NAME.value: CLASSES.RSWITCH_AUDIO_DESC.value,
    CLASSES.RSWITCH_BUS_NAME.value: CLASSES.RSWITCH_BUS_DESC.value,
    CLASSES.RSWITCH_CLIP_NAME.value: CLASSES.RSWITCH_CLIP_DESC.value,
    CLASSES.RSWITCH_CONDITIONING_NAME.value: CLASSES.RSWITCH_CONDITIONING_DESC.value,
    CLASSES.RSWITCH_CONTROLNET_NAME.value: CLASSES.RSWITCH_CONTROLNET_DESC.value,
    CLASSES.RSWITCH_FLOAT_NAME.value: CLASSES.RSWITCH_FLOAT_DESC.value,
    CLASSES.RSWITCH_GUIDER_NAME.value: CLASSES.RSWITCH_GUIDER_DESC.value,
    CLASSES.RSWITCH_IMAGE_NAME.value: CLASSES.RSWITCH_IMAGE_DESC.value,
    CLASSES.RSWITCH_INTEGER_NAME.value: CLASSES.RSWITCH_INTEGER_DESC.value,
    CLASSES.RSWITCH_LATENT_NAME.value: CLASSES.RSWITCH_LATENT_DESC.value,
    CLASSES.RSWITCH_MASK_NAME.value: CLASSES.RSWITCH_MASK_DESC.value,
    CLASSES.RSWITCH_MODEL_NAME.value: CLASSES.RSWITCH_MODEL_DESC.value,
    CLASSES.RSWITCH_BASIC_PIPE_NAME.value: CLASSES.RSWITCH_BASIC_PIPE_DESC.value,
    CLASSES.RSWITCH_DETAILER_PIPE_NAME.value: CLASSES.RSWITCH_DETAILER_PIPE_DESC.value,
    CLASSES.RSWITCH_STRING_NAME.value: CLASSES.RSWITCH_STRING_DESC.value,
    CLASSES.RSWITCH_VAE_NAME.value: CLASSES.RSWITCH_VAE_DESC.value,
    CLASSES.RMULTISWITCH_MODEL_NAME.value: CLASSES.RMULTISWITCH_MODEL_DESC.value,
    CLASSES.RMULTISWITCH_CLIP_NAME.value: CLASSES.RMULTISWITCH_CLIP_DESC.value,
    CLASSES.RMULTISWITCH_VAE_NAME.value: CLASSES.RMULTISWITCH_VAE_DESC.value,
    CLASSES.RMULTISWITCH_LATENT_NAME.value: CLASSES.RMULTISWITCH_LATENT_DESC.value,
    #passer
    CLASSES.RPASS_AUDIO_NAME.value: CLASSES.RPASS_AUDIO_DESC.value,
    CLASSES.RPASS_CLIP_NAME.value: CLASSES.RPASS_CLIP_DESC.value,
    CLASSES.RPASS_CONDITIONING_NAME.value: CLASSES.RPASS_CONDITIONING_DESC.value,
    CLASSES.RPASS_FLOAT_NAME.value: CLASSES.RPASS_FLOAT_DESC.value,
    CLASSES.RPASS_IMAGE_NAME.value: CLASSES.RPASS_IMAGE_DESC.value,
    CLASSES.RPASS_INTEGER_NAME.value: CLASSES.RPASS_INTEGER_DESC.value,
    CLASSES.RPASS_LATENT_NAME.value: CLASSES.RPASS_LATENT_DESC.value,
    CLASSES.RPASS_MASK_NAME.value: CLASSES.RPASS_MASK_DESC.value,
    CLASSES.RPASS_MODEL_NAME.value: CLASSES.RPASS_MODEL_DESC.value,
    CLASSES.RPASS_PIPE_BASIC_NAME.value: CLASSES.RPASS_PIPE_BASIC_DESC.value,
    CLASSES.RPASS_PIPE_DETAILER_NAME.value: CLASSES.RPASS_PIPE_DETAILER_DESC.value,
    CLASSES.RPASS_PIPE_LINE_NAME.value: CLASSES.RPASS_PIPE_LINE_DESC.value,
    CLASSES.RPASS_STRING_NAME.value: CLASSES.RPASS_STRING_DESC.value,
    CLASSES.RPASS_SAMPLER_NAME.value: CLASSES.RPASS_SAMPLER_DESC.value,
    CLASSES.RPASS_SCHEDULER_COMFYUI_NAME.value: CLASSES.RPASS_SCHEDULER_COMFYUI_DESC.value,
    CLASSES.RPASS_SCHEDULER_IMPACT_NAME.value: CLASSES.RPASS_SCHEDULER_IMPACT_DESC.value,
    CLASSES.RPASS_SCHEDULER_EFFICIENT_NAME.value: CLASSES.RPASS_SCHEDULER_EFFICIENT_DESC.value,
    CLASSES.RPASS_SCHEDULER_RESTART_NAME.value: CLASSES.RPASS_SCHEDULER_RESTART_DESC.value,

    #utils
    CLASSES.RBUS_ANY_8CH_IN_NAME.value: CLASSES.RBUS_ANY_8CH_IN_DESC.value,
    CLASSES.RBUS_ANY_8CH_OUT_NAME.value: CLASSES.RBUS_ANY_8CH_OUT_DESC.value,
    CLASSES.RBUS_ANY_12CH_IN_NAME.value: CLASSES.RBUS_ANY_12CH_IN_DESC.value,
    CLASSES.RBUS_ANY_12CH_OUT_NAME.value: CLASSES.RBUS_ANY_12CH_OUT_DESC.value,
    CLASSES.RREPLACE_STRING_NAME.value: CLASSES.RREPLACE_STRING_DESC.value,
    CLASSES.RMERGE_STRING_NAME.value: CLASSES.RMERGE_STRING_DESC.value,
    CLASSES.RMERGE_STRING_LARGE_NAME.value: CLASSES.RMERGE_STRING_LARGE_DESC.value,
    CLASSES.RINTEGER_TO_STRING_NAME.value: CLASSES.RINTEGER_TO_STRING_DESC.value,
    CLASSES.RFLOAT_TO_STRING_NAME.value: CLASSES.RFLOAT_TO_STRING_DESC.value,
    CLASSES.RFLOAT_TO_INTEGER_NAME.value: CLASSES.RFLOAT_TO_INTEGER_DESC.value,
    CLASSES.RSIZES_PLUS_XY_NAME.value: CLASSES.RSIZES_PLUS_XY_DESC.value,
    CLASSES.RSTRINGLIST_TO_COMBO_NAME.value: CLASSES.RSTRINGLIST_TO_COMBO_DESC.value,
    CLASSES.RCOMBO_TO_STRING_NAME.value: CLASSES.RCOMBO_TO_STRING_DESC.value,
    CLASSES.RIFEXECUTE_NAME.value: CLASSES.RIFEXECUTE_DESC.value,
    

}


#WEB_DIRECTORY = "./web"
